agentic.version=2.4.4
spring.application.name=agentic-backend
server.port=8080
spring.main.allow-circular-references=true
spring.aop.proxy-target-class=false
spring.datasource.url=jdbc:h2:file:${user.home}/.agentic/db/agentic_db;AUTO_SERVER=TRUE;LOCK_TIMEOUT=10000;WRITE_DELAY=0
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=agentic123
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.bytecode.provider=bytebuddy

plugins.registry.url=https://raw.githubusercontent.com/akumosstl/akumosstl.github.io/main/plugins.json

logging.level.root=ERROR
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.agentic=ERROR
logging.level.io.github.akumosstl.agentic.backend.controller.ProjectController=INFO
logging.level.org.springframework.boot.SpringApplication=ERROR
logging.level.org.springframework.boot.logging=ERROR

spring.main.banner-mode=off
logging.pattern.console=%msg%n
logging.pattern.file=%msg%n