import { Component, Inject, HostListener, NgZone, ChangeDetectorRef } from '@angular/core'
import { MatDialogRef, MAT_DIALOG_DATA, MatDialogModule } from '@angular/material/dialog'
import { MatButtonModule } from '@angular/material/button'
import { MatIconModule } from '@angular/material/icon'
import { CommonModule } from '@angular/common'
import { ApiService } from '../../services/api.service'

@Component({
  selector: 'app-import-namespace-dialog',
  standalone: true,
  imports: [CommonModule, MatDialogModule, MatButtonModule, MatIconModule],
  template: `
    <h2 mat-dialog-title>
      <mat-icon>file_upload</mat-icon>
      Import SQL
    </h2>

    <mat-dialog-content>
      <div class="import-section" *ngIf="!importResult">
        <p class="info-text">Select a <strong>.sql</strong> file generated by the Export function to import agents or scripts.</p>

        <div class="file-input-wrapper">
          <button mat-raised-button color="primary" (click)="fileInput.click()" class="choose-file-btn">
            <mat-icon>folder_open</mat-icon>
            Choose File
          </button>
          <input #fileInput type="file" accept=".sql" (change)="onFileSelected($event)" hidden />
          <span class="file-name" *ngIf="selectedFile">{{ selectedFile.name }}</span>
          <span class="file-name no-file" *ngIf="!selectedFile">No file selected</span>
        </div>

        <div class="preview-section" *ngIf="fileContent">
          <div class="preview-header">
            <mat-icon>preview</mat-icon>
            <span>Preview</span>
          </div>
          <pre class="sql-preview">{{ fileContent.length > 500 ? fileContent.substring(0, 500) + '...' : fileContent }}</pre>
        </div>
      </div>

      <div class="result-section" *ngIf="importResult">
        <div class="result-header" [class.success]="importResult.success" [class.error]="!importResult.success">
          <mat-icon>{{ importResult.success ? 'check_circle' : 'error' }}</mat-icon>
          <span>{{ importResult.success ? 'Import Completed' : 'Import Failed' }}</span>
        </div>
        <p class="result-message">{{ importResult.message }}</p>

        <div *ngIf="importResult.imported?.length" class="result-list">
          <div class="list-title success-title">
            <mat-icon>add_circle</mat-icon>
            <span>Imported ({{ importResult.imported.length }})</span>
          </div>
          <div class="list-item" *ngFor="let item of importResult.imported">
            <mat-icon>check</mat-icon>
            <span>{{ item }}</span>
          </div>
        </div>

        <div *ngIf="importResult.skipped?.length" class="result-list">
          <div class="list-title skip-title">
            <mat-icon>skip_next</mat-icon>
            <span>Skipped ({{ importResult.skipped.length }})</span>
          </div>
          <div class="list-item skipped" *ngFor="let item of importResult.skipped">
            <mat-icon>remove_circle_outline</mat-icon>
            <span>{{ item }}</span>
          </div>
        </div>

        <div *ngIf="importResult.errors?.length" class="result-list">
          <div class="list-title error-title">
            <mat-icon>error</mat-icon>
            <span>Errors ({{ importResult.errors.length }})</span>
          </div>
          <div class="list-item error" *ngFor="let err of importResult.errors">
            <mat-icon>close</mat-icon>
            <span>{{ err }}</span>
          </div>
        </div>
      </div>
    </mat-dialog-content>

    <mat-dialog-actions align="end">
      <button mat-button (click)="dialogRef.close()">
        {{ importResult ? 'Close' : 'Cancel' }}
      </button>
      <button mat-raised-button color="primary"
              (click)="doImport()"
              [disabled]="!fileContent || importing || !!importResult"
              *ngIf="!importResult">
        <mat-icon *ngIf="!importing">file_upload</mat-icon>
        <span *ngIf="importing">Importing...</span>
        <span *ngIf="!importing">Import</span>
      </button>
    </mat-dialog-actions>
  `,
  styles: [`
    h2 {
      display: flex;
      align-items: center;
      gap: 10px;
      color: #e0e0e0;
    }

    h2 mat-icon {
      color: #4fc3f7;
    }

    .info-text {
      color: #b0b0b0;
      font-size: 0.9rem;
      margin-bottom: 16px;
    }

    .file-input-wrapper {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 16px;
    }

    .choose-file-btn {
      display: flex;
      align-items: center;
      gap: 6px;
    }

    .file-name {
      color: #e0e0e0;
      font-size: 0.85rem;
    }

    .file-name.no-file {
      color: #666;
      font-style: italic;
    }

    .preview-section {
      border: 1px solid #2a2a2a;
      border-radius: 8px;
      overflow: hidden;
    }

    .preview-header {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 8px 12px;
      background: #1e1e1e;
      border-bottom: 1px solid #2a2a2a;
      color: #888;
      font-size: 0.8rem;
    }

    .preview-header mat-icon {
      font-size: 16px;
      width: 16px;
      height: 16px;
    }

    .sql-preview {
      padding: 12px;
      background: #0d0d0d;
      color: #b0b0b0;
      font-family: monospace;
      font-size: 0.8rem;
      max-height: 200px;
      overflow-y: auto;
      margin: 0;
      white-space: pre-wrap;
      word-break: break-all;
    }

    .result-header {
      display: flex;
      align-items: center;
      gap: 10px;
      padding: 12px 16px;
      border-radius: 8px;
      margin-bottom: 12px;
      font-size: 1rem;
      font-weight: 600;
    }

    .result-header.success {
      background: #1b5e20;
      color: #a5d6a7;
    }

    .result-header.error {
      background: #b71c1c;
      color: #ef9a9a;
    }

    .result-message {
      color: #b0b0b0;
      font-size: 0.9rem;
      margin-bottom: 16px;
    }

    .result-list {
      margin-bottom: 12px;
    }

    .list-title {
      display: flex;
      align-items: center;
      gap: 6px;
      font-size: 0.85rem;
      font-weight: 600;
      margin-bottom: 6px;
    }

    .list-title mat-icon {
      font-size: 18px;
      width: 18px;
      height: 18px;
    }

    .success-title {
      color: #a5d6a7;
    }

    .skip-title {
      color: #ffe082;
    }

    .error-title {
      color: #ef9a9a;
    }

    .list-item {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 6px 12px;
      color: #e0e0e0;
      font-size: 0.85rem;
    }

    .list-item mat-icon {
      font-size: 16px;
      width: 16px;
      height: 16px;
    }

    .list-item.skipped {
      color: #ffe082;
    }

    .list-item.skipped mat-icon {
      color: #ffc107;
    }

    .list-item.error {
      color: #ef9a9a;
    }

    .list-item.error mat-icon {
      color: #f44336;
    }
  `]
})
export class ImportNamespaceDialogComponent {
  selectedFile: File | null = null
  fileContent: string | null = null
  importing = false
  importResult: any = null

  constructor(
    public dialogRef: MatDialogRef<ImportNamespaceDialogComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    private apiService: ApiService,
    private ngZone: NgZone,
    private cdr: ChangeDetectorRef
  ) {}

  @HostListener('document:keydown.control.enter')
  onCtrlEnter(): void {
    if (this.fileContent && !this.importing && !this.importResult) {
      this.doImport()
    }
  }

  onFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement
    if (input.files && input.files.length > 0) {
      this.selectedFile = input.files[0]
      const reader = new FileReader()
      reader.onload = (e) => {
        this.ngZone.run(() => {
          this.fileContent = e.target?.result as string
          this.cdr.detectChanges()
        })
      }
      reader.readAsText(this.selectedFile)
    }
  }

  doImport(): void {
    if (!this.fileContent) return

    this.importing = true
    this.apiService.importNamespace(this.fileContent).subscribe({
      next: (result) => {
        this.ngZone.run(() => {
          this.importing = false
          this.importResult = result
          this.cdr.detectChanges()
        })
      },
      error: (err) => {
        this.ngZone.run(() => {
          this.importing = false
          this.importResult = {
            success: false,
            message: 'Error during import: ' + (err.message || 'Unknown error'),
            errors: [err.message || 'Unknown error'],
            imported: [],
            skipped: []
          }
          this.cdr.detectChanges()
        })
      }
    })
  }
}
